apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: multi-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      imagePullSecrets:
      - name: ghcr-secret

      containers:
      - name: backend

        image: ghcr.io/sridevi0616/backend:v2

        ports:
        - containerPort: 5000
